[build]
  command = " npm run build && npm i --prefix=functions"
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/portfolio"
  to = "https://portfolio.selftaught-dev.com/"
  status = 301
  force = true
